import type { Metadata } from "next";
import "./globals.css";
import { IranYekan } from "@/utils/fonts";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode,
}>) {


  return (
    <html lang="fa" dir="rtl" className="dark">
      <body className={`${IranYekan.className} antialiased bg-[url(/images/other/background.jpg)] bg-repeat `}>

          {children}

      </body>
    </html>
  );
}
