import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { IranYekan } from "@/utils/fonts";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode,
  params: Promise<{ locale: string }>
}>) {


  return (
    <html lang="fa" dir="rtl" className="dark">
      <body className={`${IranYekan.className} antialiased bg-[url(/images/other/background.jpg)] bg-repeat `}>

          <Navbar></Navbar>
          {children}

      </body>
    </html>
  );
}
